### ISSUE TITLE
Create the option --classes names

### ISSUE THREAD

**Issue by andvasp** [forax/einherjar#1]
How about the possibility of option --classes where the user can directly specify the value classes to be enhanced?

This would be valuable for flexibility and cases where the libraries will not be changed but meet the requirements of value types.

**Comment by forax** [comment]
Fixed by commit https://github.com/forax/einherjar/commit/59054c4508a94a9f19c9c1aea8454c63eb043fe8

**Comment by andvasp** [comment]
Great!!

Thanks!
